import type { Metadata } from 'next'
import "@/styles/globals.css"
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
    title: 'DuYi Demo',
    description: 'Generated by create next app'
}

interface RootLayoutProps {
    children: React.ReactNode,
}

export default function RootLayout({
    children
}: Readonly<RootLayoutProps>) {
    return (
        <html lang="en">
            <body className='antialiased'>
                {children}
                <Toaster />
            </body>
        </html>
    )
}
